import { QRPreset } from "@/interface";

export const QR_PRESETS: QRPreset[] = [
  {
    id: "classic",
    name: "Classic",
    pattern: { type: "squares" },
    cornerStyle: { type: "square" },
    frame: { style: "classic" },
  },
  {
    id: "rounded",
    name: "Rounded Dots",
    pattern: { type: "dots", moduleSize: 0.5 },
    cornerStyle: { type: "rounded", radius: 8 },
    frame: { style: "rounded", padding: 16 },
  },
  {
    id: "elegant",
    name: "Elegant Square",
    pattern: { type: "squares" },
    cornerStyle: { type: "extraRound", radius: 12 },
    frame: { style: "shadow" },
  },
  {
    id: "minimal-dots",
    name: "Minimal Dots",
    pattern: { type: "dots", moduleSize: 0.4 },
    cornerStyle: { type: "dots" },
    frame: { style: "minimal" },
  },
  {
    id: "classy-rounded",
    name: "Classy Rounded",
    pattern: { type: "rounded", cornerRadius: 4 },
    cornerStyle: { type: "rounded", radius: 8 },
    frame: { style: "classic" },
  },
  {
    id: "modern-square",
    name: "Modern Square",
    pattern: { type: "squares" },
    cornerStyle: { type: "square" },
    frame: { style: "minimal" },
  },
  {
    id: "dotted-elegant",
    name: "Dotted Elegant",
    pattern: { type: "dots", moduleSize: 0.45 },
    cornerStyle: { type: "rounded", radius: 10 },
    frame: { style: "shadow" },
  },
  {
    id: "rounded-corners",
    name: "Rounded Corners",
    pattern: { type: "squares" },
    cornerStyle: { type: "rounded", radius: 6 },
    frame: { style: "rounded" },
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect",
    pattern: { type: "squares" },
    cornerStyle: { type: "square" },
    frame: { style: "none" },
  },
  {
    id: "smooth-dots",
    name: "Smooth Dots",
    pattern: { type: "dots", moduleSize: 0.5 },
    cornerStyle: { type: "dots" },
    frame: { style: "minimal" },
  },
  {
    id: "professional",
    name: "Professional",
    pattern: { type: "squares" },
    cornerStyle: { type: "square" },
    frame: { style: "classic" },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    pattern: { type: "rounded", cornerRadius: 2 },
    cornerStyle: { type: "rounded", radius: 4 },
    frame: { style: "minimal" },
  },
  {
    id: "tech-style",
    name: "Tech Style",
    pattern: { type: "dots", moduleSize: 0.6 },
    cornerStyle: { type: "square" },
    frame: { style: "shadow" },
  },
  {
    id: "corporate",
    name: "Corporate",
    pattern: { type: "squares" },
    cornerStyle: { type: "extraRound", radius: 10 },
    frame: { style: "classic" },
  },
  {
    id: "bold-minimal",
    name: "Bold Minimal",
    pattern: { type: "squares" },
    cornerStyle: { type: "rounded", radius: 8 },
    frame: { style: "none" },
  },
];
